/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AiDetectionRouteImport } from './routes/ai-detection'
import { Route as IndexRouteImport } from './routes/index'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDetectionRoute = AiDetectionRouteImport.update({
  id: '/ai-detection',
  path: '/ai-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/logs': typeof LogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/logs': typeof LogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/logs': typeof LogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-detection' | '/logs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-detection' | '/logs'
  id: '__root__' | '/' | '/ai-detection' | '/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDetectionRoute: typeof AiDetectionRoute
  LogsRoute: typeof LogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-detection': {
      id: '/ai-detection'
      path: '/ai-detection'
      fullPath: '/ai-detection'
      preLoaderRoute: typeof AiDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDetectionRoute: AiDetectionRoute,
  LogsRoute: LogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
