/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoarRouteImport } from './routes/soar'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AiDetectionRouteImport } from './routes/ai-detection'
import { Route as IndexRouteImport } from './routes/index'

const SoarRoute = SoarRouteImport.update({
  id: '/soar',
  path: '/soar',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDetectionRoute = AiDetectionRouteImport.update({
  id: '/ai-detection',
  path: '/ai-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/billing': typeof BillingRoute
  '/logs': typeof LogsRoute
  '/soar': typeof SoarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/billing': typeof BillingRoute
  '/logs': typeof LogsRoute
  '/soar': typeof SoarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/billing': typeof BillingRoute
  '/logs': typeof LogsRoute
  '/soar': typeof SoarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-detection' | '/billing' | '/logs' | '/soar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-detection' | '/billing' | '/logs' | '/soar'
  id: '__root__' | '/' | '/ai-detection' | '/billing' | '/logs' | '/soar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDetectionRoute: typeof AiDetectionRoute
  BillingRoute: typeof BillingRoute
  LogsRoute: typeof LogsRoute
  SoarRoute: typeof SoarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soar': {
      id: '/soar'
      path: '/soar'
      fullPath: '/soar'
      preLoaderRoute: typeof SoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-detection': {
      id: '/ai-detection'
      path: '/ai-detection'
      fullPath: '/ai-detection'
      preLoaderRoute: typeof AiDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDetectionRoute: AiDetectionRoute,
  BillingRoute: BillingRoute,
  LogsRoute: LogsRoute,
  SoarRoute: SoarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
